title: "&8-=( &7Einstellungen &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Pazifistisch{$colon} %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7Wenn du im pazifischen-Modus bist,"
      - "kan ndein Königreich nicht angegriffen werden"
      - "und kann keine anderen Königreiche erobern."
      - ""
      - "Wenn du ein anderes Königreich eroberst,"
      - "kannst du für eine Woche nicht in den Mudus zurückkehren."
      - ""
      - "&2Cooldown{$colon} &6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Schild{$colon} &2%time@kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Kaufe ein Schild für dein"
      - "Königreich, um es gegen"
      - "Angreifer zu schützen."
    posx: 2
    posy: 1
  invites:
    name: "&6Einladungen{$colon} %invites%"
    material: BOOK
    lore:
      - "&7Wenn es deaktiviert ist,"
      - "kann jeder das Königreich mit"
      - "&2/k nation join %kingdoms_nation_name% &7beitreten."
    posx: 3
    posy: 1
  relations:
    name: "&6Beziehungen"
    material: WRITABLE_BOOK
    lore:
      - "&7Ändert die Beziehungs-Attrbute"
      - "zu anderen Königreichen."
    posx: 4
    posy: 1
  tax:
    name: "&6Steuer"
    material: PAPER
    lore:
      - "&7Ändere die königlichen Steuern"
      - "für Mitglieder."
      - ""
      - "&6Steuer{$colon} &2$%fancy@kingdoms_nation_tax%"
      - "&6Gleichung{$colon} &2%tax_equation%"
      - ""
      - "&6Abrechnungssteuer{$colon} &2$%fancy@kingdoms_server_nation_tax%"
    posx: 5
    posy: 1
  public-home:
    name: "&6Öffentliches Zuhause{$colon} &2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&7Du kannst dein Zuhause öffentlich machen,"
      - "damit andere Spieler es besuchen können."
      - "Befehl: &6/k home %kingdoms_kingdom_name%"
    posx: 6
    posy: 1
  flag:
    name: "&6Flagge"
    material: BLACK_BANNER
    lore:
      - "&7Setze deine Flagge für Dynmap fest."
      - "Klicke, um deine Fallegn-URL zu sehen."
      - "Dies wird allerdings die Karte nicht direkt updaten."
    posx: 7
    posy: 1
  color:
    name: "&6Farbe{$colon} &c%r%&7, &2%g%&7, &9%b% &7(&d%hex%&7)"
    material: BLACK_DYE
    lore:
      - "&7Legt deinen Königreichs-Farbe"
      - "für Dynmap fest."
      - "Dies wird allerdings die Karte nicht direkt updaten."
    posx: 8
    posy: 1

  back:
    name: "&2Back"
    material: PLAYER_HEAD
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Gehe zurück zum Nexus-Menü."
    posx: 9
    posy: 1