title: "{$sep}-=( &7Einstellungen {$sep})=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Schild{$colon} &2%time@kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Kaufe ein Schild für dein"
      - "Königreich, um es gegen"
      - "Angreifer zu schützen."
    posx: 1
    posy: 1
  invites:
    name: "&6Einladungen{$colon} %invites%"
    material: BOOK
    lore:
      - "&7Wenn es deaktiviert ist,"
      - "kann jeder das Königreich mit"
      - "&2/k nation join %kingdoms_nation_name% &7beitreten."
    posx: 2
    posy: 1
  relations:
    name: "&6Beziehungen"
    material: WRITABLE_BOOK
    lore:
      - "&7Ändere den Beziehungs-Status"
      - "zu anderen Königreichen."
    posx: 3
    posy: 1
  tax:
    name: "&6Steuer"
    material: PAPER
    lore:
      - "&7Ändere die königlichen Steuern"
      - "für Mitglieder."
      - ""
      - "&6Steuer{$colon} &2$%fancy@kingdoms_nation_tax%"
      - "&6Gleichung{$colon} &2%tax_equation%"
      - ""
      - "&6Abrechnungssteuer{$colon} &2$%fancy@kingdoms_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Zurück"
    material: PLAYER_HEAD
    skull: "{$gui-back}"
    lore:
      - "&6Gehe zurück zum Nexus-Menü."
    posx: 9
    posy: 1