title: "&8-=( &2Bajnok beállításai &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bFelszerelés fejlesztése"
    material: DIAMOND_CHESTPLATE
    sounds:
      max-level: BLOCK_NOTE_BLOCK_BASS
      not-enough-resource-points: BLOCK_NOTE_BLOCK_BASS
      upgraded: ENTITY_EXPERIENCE_ORB_PICKUP
    lore:
      - "&7Javítsd fel a Bajnok"
      - "páncélzatát és fegyverét."
      - ""
      - "&2Szint&8: &6%level%"
      - "&2Ár&8: &6%cost%"
    slot: 0
  change:
    name: "&6Váltás"
    material: DIAMOND_SWORD
    lore:
      - "&7Bajnok típusának váltása."
    slot: 1

  back:
    name: "&2Vissza"
    material: BARRIER
    slot: 4