title: "{$sep}-=( &2Налаштування Чемпіонів {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bПокращити Обладнання"
    material: DIAMOND_CHESTPLATE
    lore:
      - "&7Покращуйте броню та зброю вашого чемпіона з кожним оновленням."
      - ""
      - "&2Рівень{$colon} &6%level%"
      - "&2Вартість{$colon} &6%cost%"
    slot: 0
  change:
    name: "&6Змінити"
    material: DIAMOND_SWORD
    lore:
      - "&7Змініть тип вашого чемпіона."
    slot: 1

  back:
    name: "&2Назад"
    material: BARRIER
    lore:
      - "&6Повернутися до покращень чемпіонів."
    slot: 4