title: "&8Настройка защитника"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bОбновление"
    material: IRON_CHESTPLATE
    sounds:
      max-%level%: BLOCK_NOTE_BLOCK_BASS
      not-enough-resource-points: BLOCK_NOTE_BLOCK_BASS
      upgraded: ENTITY_EXPERIENCE_ORB_PICKUP
    lore:
      - "&7Улучшайте доспехи и оружие своих"
      - "чемпионов с каждым обновлением"
      - ""
      - "&8▪ &7Уровень &8» &b%level%"
      - "&8▪ &7Стоимость &8» &e%cost% оч.ресурсов"
    slot: 0
  change:
    name: "&6Сменить тип"
    material: IRON_SWORD
    lore:
      - "&7Изменить тип защитника"
    slot: 1

  back:
    name: "&cНазад"
    material: BARRIER
    lore:
      - ""
    slot: 4