title: "&8Настройки"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Щит&8: &b%kingdoms_time_shield_time_left%"
    material: SHIELD
    lore:
      - "&8▪ &7Купите щит для своей"
      - "нации чтобы защитить"
      - "её от вторжений"
    posx: 1
    posy: 1
  invites:
    name: "&6Приглашения&8: %invites%"
    material: BOOK
    lore:
      - "&8▪ &7Если этот параметр отключен, любой может"
      - "присоединиться к этой нации без"
      - "приглашения с помощью &e/k nation join %kingdoms_nation_name%"
    posx: 2
    posy: 1
  relations:
    name: "&6Отношения"
    material: WRITABLE_BOOK
    lore:
      - "&8▪ &7Измените свои атрибуты отношений"
      - "для других королевств"
    posx: 3
    posy: 1
  tax:
    name: "&6Налоги"
    material: PAPER
    lore:
      - "&8▪ &7Измените уравление"
      - "национальных налогов для королевств."
      - ""
      - "&8▪ &7Налог&8: &e%kingdoms_fancy_nation_tax% монет"
      - "&8▪ &7Уравнение&8: &9%tax_equation%"
      - ""
      - "&8▪ &7Налог для выставления счетов&8: &b%kingdoms_fancy_server_nation_tax% монет"
      - ""
      - " &bНажмите, чтобы установить &aуравнение&7"
      - "  (пример: (money) * 5 / 100)"
    posx: 4
    posy: 1

  back:
    name: "&cНазад"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - ""
    posx: 9
    posy: 1