title: "&8Настройки"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Щит{$colon} &b%time@kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&8▪ &7Купите щит для своей"
      - "нации чтобы защитить"
      - "её от вторжений"
    posx: 1
    posy: 1
  invites:
    name: "&6Приглашения{$colon} %invites%"
    material: BOOK
    lore:
      - "&8▪ &7Если этот параметр отключен, любой может"
      - "присоединиться к этой нации без"
      - "приглашения с помощью &e/k nation join %kingdoms_nation_name%"
    posx: 2
    posy: 1
  relations:
    name: "&6Отношения"
    material: WRITABLE_BOOK
    lore:
      - "&8▪ &7Измените свои атрибуты отношений"
      - "для других королевств"
    posx: 3
    posy: 1
  tax:
    name: "&6Налоги"
    material: PAPER
    lore:
      - "&8▪ &7Измените уравление"
      - "национальных налогов для королевств."
      - ""
      - "&8▪ &7Налог{$colon} &e%fancy@kingdoms_nation_tax% монет"
      - "&8▪ &7Уравнение{$colon} &9%tax_equation%"
      - ""
      - "&8▪ &7Налог для выставления счетов{$colon} &b%fancy@kingdoms_server_nation_tax% монет"
      - ""
      - " &bНажмите, чтобы установить &aуравнение&7"
      - "  (пример: (money) * 5 / 100)"
    posx: 4
    posy: 1

  back:
    name: "&cНазад"
    material: PLAYER_HEAD
    sound: default
    skull: "{$gui-back}"
    lore:
      - ""
    posx: 9
    posy: 1