files:
- source: core/src/main/resources/guis/addons.yml
  translation: /resources/languages/%two_letters_code%/guis/addons.yml
- source: core/src/main/resources/guis/book.yml
  translation: /resources/languages/%two_letters_code%/guis/book.yml
- source: core/src/main/resources/guis/challenge.yml
  translation: /resources/languages/%two_letters_code%/guis/challenge.yml
- source: core/src/main/resources/guis/election-candidates.yml
  translation: /resources/languages/%two_letters_code%/guis/election-candidates.yml
- source: core/src/main/resources/guis/error.yml
  translation: /resources/languages/%two_letters_code%/guis/error.yml
- source: core/src/main/resources/guis/input.yml
  translation: /resources/languages/%two_letters_code%/guis/input.yml
- source: core/src/main/resources/guis/invite-codes.yml
  translation: /resources/languages/%two_letters_code%/guis/invite-codes.yml
- source: core/src/main/resources/guis/invites.yml
  translation: /resources/languages/%two_letters_code%/guis/invites.yml
- source: core/src/main/resources/guis/invsee.yml
  translation: /resources/languages/%two_letters_code%/guis/invsee.yml
- source: core/src/main/resources/guis/kingdom-create.yml
  translation: /resources/languages/%two_letters_code%/guis/kingdom-create.yml
- source: core/src/main/resources/guis/kingdom-join-requests.yml
  translation: /resources/languages/%two_letters_code%/guis/kingdom-join-requests.yml
- source: core/src/main/resources/guis/kingdom-relation-requests.yml
  translation: /resources/languages/%two_letters_code%/guis/kingdom-relation-requests.yml
- source: core/src/main/resources/guis/language-packs.yml
  translation: /resources/languages/%two_letters_code%/guis/language-packs.yml
- source: core/src/main/resources/guis/languages.yml
  translation: /resources/languages/%two_letters_code%/guis/languages.yml
- source: core/src/main/resources/guis/map-settings.yml
  translation: /resources/languages/%two_letters_code%/guis/map-settings.yml
- source: core/src/main/resources/guis/map.yml
  translation: /resources/languages/%two_letters_code%/guis/map.yml
- source: core/src/main/resources/guis/surrender.yml
  translation: /resources/languages/%two_letters_code%/guis/surrender.yml
- source: core/src/main/resources/guis/unclaimed-kingdom-item.yml
  translation: /resources/languages/%two_letters_code%/guis/unclaimed-kingdom-item.yml
- source: core/src/main/resources/guis/bossbar/bossbar/colors.yml
  translation: /resources/languages/%two_letters_code%/guis/bossbar/colors.yml
- source: core/src/main/resources/guis/bossbar/bossbar/editor.yml
  translation: /resources/languages/%two_letters_code%/guis/bossbar/editor.yml
- source: core/src/main/resources/guis/bossbar/bossbar/flags.yml
  translation: /resources/languages/%two_letters_code%/guis/bossbar/flags.yml
- source: core/src/main/resources/guis/bossbar/bossbar/styles.yml
  translation: /resources/languages/%two_letters_code%/guis/bossbar/styles.yml
- source: core/src/main/resources/guis/confirm/confirm/disband.yml
  translation: /resources/languages/%two_letters_code%/guis/confirm/disband.yml
- source: core/src/main/resources/guis/confirm/confirm/unclaimall.yml
  translation: /resources/languages/%two_letters_code%/guis/confirm/unclaimall.yml
- source: core/src/main/resources/guis/confirm/ranks/confirm/ranks/demote-all.yml
  translation: /resources/languages/%two_letters_code%/guis/confirm/ranks/demote-all.yml
- source: core/src/main/resources/guis/confirm/ranks/confirm/ranks/reset.yml
  translation: /resources/languages/%two_letters_code%/guis/confirm/ranks/reset.yml
- source: core/src/main/resources/guis/item-editor/item-editor/enchantments.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/enchantments.yml
- source: core/src/main/resources/guis/item-editor/item-editor/flags.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/flags.yml
- source: core/src/main/resources/guis/item-editor/item-editor/main.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/main.yml
- source: core/src/main/resources/guis/item-editor/item-editor/nbt-types.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/nbt-types.yml
- source: core/src/main/resources/guis/item-editor/item-editor/nbt.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/nbt.yml
- source: core/src/main/resources/guis/item-editor/attributes/item-editor/attributes/editor.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/attributes/editor.yml
- source: core/src/main/resources/guis/item-editor/attributes/item-editor/attributes/equipment-slots.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/attributes/equipment-slots.yml
- source: core/src/main/resources/guis/item-editor/attributes/item-editor/attributes/list.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/attributes/list.yml
- source: core/src/main/resources/guis/item-editor/attributes/item-editor/attributes/operations.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/attributes/operations.yml
- source: core/src/main/resources/guis/item-editor/attributes/item-editor/attributes/types.yml
  translation: /resources/languages/%two_letters_code%/guis/item-editor/attributes/types.yml
- source: core/src/main/resources/guis/mails/mails/editor.yml
  translation: /resources/languages/%two_letters_code%/guis/mails/editor.yml
- source: core/src/main/resources/guis/mails/mails/mailbox.yml
  translation: /resources/languages/%two_letters_code%/guis/mails/mailbox.yml
- source: core/src/main/resources/guis/mails/mails/recipients.yml
  translation: /resources/languages/%two_letters_code%/guis/mails/recipients.yml
- source: core/src/main/resources/guis/outposts/outposts/editor.yml
  translation: /resources/languages/%two_letters_code%/guis/outposts/editor.yml
- source: core/src/main/resources/guis/outposts/rewards/outposts/rewards/commands.yml
  translation: /resources/languages/%two_letters_code%/guis/outposts/rewards/commands.yml
- source: core/src/main/resources/guis/outposts/rewards/outposts/rewards/items.yml
  translation: /resources/languages/%two_letters_code%/guis/outposts/rewards/items.yml
- source: core/src/main/resources/guis/outposts/rewards/outposts/rewards/main.yml
  translation: /resources/languages/%two_letters_code%/guis/outposts/rewards/main.yml
- source: core/src/main/resources/guis/protection-signs/protection-signs/kingdoms.yml
  translation: /resources/languages/%two_letters_code%/guis/protection-signs/kingdoms.yml
- source: core/src/main/resources/guis/protection-signs/protection-signs/players.yml
  translation: /resources/languages/%two_letters_code%/guis/protection-signs/players.yml
- source: core/src/main/resources/guis/protection-signs/protection-signs/protected-sign.yml
  translation: /resources/languages/%two_letters_code%/guis/protection-signs/protected-sign.yml
- source: core/src/main/resources/guis/protection-signs/protection-signs/protection-type.yml
  translation: /resources/languages/%two_letters_code%/guis/protection-signs/protection-type.yml
- source: core/src/main/resources/guis/structures/structures/extractor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/extractor.yml
- source: core/src/main/resources/guis/structures/structures/powercell.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/powercell.yml
- source: core/src/main/resources/guis/structures/structures/siege-cannon.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/siege-cannon.yml
- source: core/src/main/resources/guis/structures/structures/warppad.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/warppad.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/champion-settings.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/champion-settings.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/champion-upgrades.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/champion-upgrades.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/champions.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/champions.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/logs-filters-and-sorting.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/logs-filters-and-sorting.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/logs.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/logs.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/member.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/member.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/members.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/members.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/misc-upgrades.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/misc-upgrades.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/nexus.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nexus.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/resource-points-converter.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/resource-points-converter.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/structures.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/structures.yml
- source: core/src/main/resources/guis/structures/nexus/structures/nexus/turrets.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/turrets.yml
- source: core/src/main/resources/guis/structures/nexus/nation/structures/nexus/nation/nexus.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/nexus.yml
- source: core/src/main/resources/guis/structures/nexus/nation/structures/nexus/nation/resource-points-converter.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/resource-points-converter.yml
- source: core/src/main/resources/guis/structures/nexus/nation/ranks/structures/nexus/nation/ranks/king-rank-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/ranks/king-rank-editor.yml
- source: core/src/main/resources/guis/structures/nexus/nation/ranks/structures/nexus/nation/ranks/permissions.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/ranks/permissions.yml
- source: core/src/main/resources/guis/structures/nexus/nation/ranks/structures/nexus/nation/ranks/rank-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/ranks/rank-editor.yml
- source: core/src/main/resources/guis/structures/nexus/nation/ranks/structures/nexus/nation/ranks/rank-selector.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/ranks/rank-selector.yml
- source: core/src/main/resources/guis/structures/nexus/nation/ranks/structures/nexus/nation/ranks/ranks.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/ranks/ranks.yml
- source: core/src/main/resources/guis/structures/nexus/nation/settings/structures/nexus/nation/settings/relation-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/settings/relation-editor.yml
- source: core/src/main/resources/guis/structures/nexus/nation/settings/structures/nexus/nation/settings/relations.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/settings/relations.yml
- source: core/src/main/resources/guis/structures/nexus/nation/settings/structures/nexus/nation/settings/settings.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/settings/settings.yml
- source: core/src/main/resources/guis/structures/nexus/nation/settings/structures/nexus/nation/settings/shields.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/nation/settings/shields.yml
- source: core/src/main/resources/guis/structures/nexus/ranks/structures/nexus/ranks/king-rank-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/ranks/king-rank-editor.yml
- source: core/src/main/resources/guis/structures/nexus/ranks/structures/nexus/ranks/permissions.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/ranks/permissions.yml
- source: core/src/main/resources/guis/structures/nexus/ranks/structures/nexus/ranks/rank-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/ranks/rank-editor.yml
- source: core/src/main/resources/guis/structures/nexus/ranks/structures/nexus/ranks/rank-selector.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/ranks/rank-selector.yml
- source: core/src/main/resources/guis/structures/nexus/ranks/structures/nexus/ranks/ranks.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/ranks/ranks.yml
- source: core/src/main/resources/guis/structures/nexus/settings/structures/nexus/settings/color-picker.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/settings/color-picker.yml
- source: core/src/main/resources/guis/structures/nexus/settings/structures/nexus/settings/relation-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/settings/relation-editor.yml
- source: core/src/main/resources/guis/structures/nexus/settings/structures/nexus/settings/relations.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/settings/relations.yml
- source: core/src/main/resources/guis/structures/nexus/settings/structures/nexus/settings/settings.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/settings/settings.yml
- source: core/src/main/resources/guis/structures/nexus/settings/structures/nexus/settings/shields.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/nexus/settings/shields.yml
- source: core/src/main/resources/guis/structures/outpost/structures/outpost/1.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/outpost/1.yml
- source: core/src/main/resources/guis/structures/outpost/structures/outpost/2.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/outpost/2.yml
- source: core/src/main/resources/guis/structures/outpost/structures/outpost/amount-picker.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/outpost/amount-picker.yml
- source: core/src/main/resources/guis/structures/regulator/structures/regulator/attribute-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/regulator/attribute-editor.yml
- source: core/src/main/resources/guis/structures/regulator/structures/regulator/attributes.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/regulator/attributes.yml
- source: core/src/main/resources/guis/structures/regulator/structures/regulator/interaction-editor.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/regulator/interaction-editor.yml
- source: core/src/main/resources/guis/structures/regulator/structures/regulator/interactions.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/regulator/interactions.yml
- source: core/src/main/resources/guis/structures/regulator/structures/regulator/regulator.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/regulator/regulator.yml
- source: core/src/main/resources/guis/structures/regulator/structures/regulator/rules.yml
  translation: /resources/languages/%two_letters_code%/guis/structures/regulator/rules.yml
- source: core/src/main/resources/guis/turrets/turrets/arrow.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/arrow.yml
- source: core/src/main/resources/guis/turrets/turrets/flame.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/flame.yml
- source: core/src/main/resources/guis/turrets/turrets/healing.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/healing.yml
- source: core/src/main/resources/guis/turrets/turrets/heatbeam.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/heatbeam.yml
- source: core/src/main/resources/guis/turrets/turrets/hellfire.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/hellfire.yml
- source: core/src/main/resources/guis/turrets/turrets/inferno.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/inferno.yml
- source: core/src/main/resources/guis/turrets/turrets/psionic.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/psionic.yml
- source: core/src/main/resources/guis/turrets/turrets/soldier.yml
  translation: /resources/languages/%two_letters_code%/guis/turrets/soldier.yml
