title: "&8-=(&7设置&8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6和平主义&8:%pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7当处于和平主义中时，"
      - "你的王国不能进行侵略，"
      - "也不能被其他王国侵略。"
      - ""
      - "如果你侵略了一个王国，"
      - "你将一周内无法处于和平主义。"
      - ""
      - "&2冷却&8:&6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6护盾&8:&2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7给你的王国买一个保护它免受侵略的护盾。"
    posx: 2
    posy: 1
  invites:
    name: "&6邀请&8:%invites%"
    material: BOOK
    lore:
      - "&7当关上时，任何人都无需邀请，只需要输入&2/k join %kingdoms_name%即可加入。"
    posx: 3
    posy: 1
  relations:
    name: "&6外交关系"
    material: WRITABLE_BOOK
    lore:
      - "&7改变你与其他王国的外交关系。"
    posx: 4
    posy: 1
  tax:
    name: "&6赋税"
    material: PAPER
    lore:
      - "&7改变你王国收取成员的税款。"
      - ""
      - "&6赋税&8:&2$%kingdoms_fancy_tax%"
      - "&6税率&8:&2%tax_equation%"
      - ""
      - "&6税款&8:&2$%kingdoms_fancy_kingdom_tax%"
    posx: 5
    posy: 1
  public-home:
    name: "&6公开的家&8:&2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&7你可以公开你王国的家，"
      - "这样其他玩家可以输入&6/k home %kingdoms_name%"
      - "以访问你王国的家。"
    posx: 6
    posy: 1
  flag:
    name: "&6旗帜"
    material: BLACK_BANNER
    lore:
      - "&7设置你的王国在Dynmap(一个能与王国联动的插件)上"
      - "显示的位置。点击这里查看当前的旗帜URL。"
      - "这不会使地图立即更新。"
    posx: 7
    posy: 1
  color:
    name: "&6颜色&8:&c%r%&7,&2%g%&7,&9%b%&7(&d%hex%&7)"
    material: BLACK_DYE
    lore:
      - "&7设置你的王国在Dynmap(一个能与王国联动的插件)上"
      - "显示的土地颜色。"
      - "这不会使地图立即更新。"
    posx: 8
    posy: 1

  back:
    name: "&2返回"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6返回到核心界面。"
    posx: 9
    posy: 1