title: "&8-=( {$p}Champion Settings &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bUpgrade Equipment"
    material: DIAMOND_CHESTPLATE
    lore:
      - "{$sep}Improves your champion's"
      - "armor and weapon with each upgrade."
      - ""
      - "{$p}Level{$colon} {$s}%level%"
      - "{$p}Cost{$colon} {$s}%cost%"
    slot: 0
  change:
    name: "{$s}Change"
    material: DIAMOND_SWORD
    lore:
      - "{$sep}Change your champion type."
    slot: 1

  back:
    name: "{$p}Back"
    material: BARRIER
    lore:
      - "{$s}Go back to champion upgrades."
    slot: 4