title: "{$sep}-=( &7Configuracion {$sep})=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Escudo{$colon} &2%time@kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Compra un escudo para tu"
      - "nación para proteger a su nación"
    posx: 1
    posy: 1
  invites:
    name: "&6Invitaciones{$colon} %invites%"
    material: BOOK
    lore:
      - "&7Cuando está apagado, cualquiera puede"
      - "unirse a esta nación sin necesidad de"
      - "una invitación con &2/k nation join %kingdoms_nation_name%"
    posx: 2
    posy: 1
  relations:
    name: "&6Relaciones"
    material: WRITABLE_BOOK
    lore:
      - "&7Cambia los atributos de tu relación"
      - "con otras naciones."
    posx: 3
    posy: 1
  tax:
    name: "&6Impuesto"
    material: PAPER
    lore:
      - "&7Cambia los impuestos de tu nación"
      - "para reinos."
      - ""
      - "&6Impuesto{$colon} &2$%fancy@kingdoms_nation_tax%"
      - "&6Ecuación{$colon} &2%tax_equation%"
      - ""
      - "&6Impuesto de facturación{$colon} &2$%fancy@kingdoms_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Volver"
    material: PLAYER_HEAD
    skull: "{$gui-back}"
    lore:
      - "&6Volver al menu de la central."
    posx: 9
    posy: 1