title: "{$sep}-=( &2Configuracion de Campeones {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bActualizar equipamiento"
    material: DIAMOND_CHESTPLATE

    lore:
      - "&7Mejora a tus campeones, la"
      - "armadura y el arma con cada mejora."
      - ""
      - "&2Nivel{$colon} &6%level%"
      - "&2Costo{$colon} &6%cost%"
    slot: 0
  change:
    name: "&6Cambiar"
    material: DIAMOND_SWORD
    lore:
      - "&7Cambia el tipo de tu campeón."
    slot: 1

  back:
    name: "&2Volver"
    material: BARRIER
    lore:
      - "&6Volver a las mejoras de campeones."
    slot: 4