title: Message
rows: int # Range handled internally
#type: handled internally
sound: Sound
interactable:
  - { (type): set, (elements): int }
  - [ "empty" ]
disallow-creative: bool
message: Message
open-options:
  (keys): Condition
  (values): Message

options:
  (values):
    (extends): ItemStack
    interaction: Enum<org.kingdoms.gui.objects.GUIInteractionType>
    condition: str
    sound: Sound
    refresh: bool
    message: Message
    # Slot ranges are handled internally.
    slot: int
    posx: int
    posy: int
    slots:
      (type): list # Not a set, duplicates are handled internally
      (elements): int