title: "&8-=( &7Configuracion &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Pacifismo&8: %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7Cuando estás en modo pacífico,"
      - "tu reino no puede invadir"
      - "y no puede ser invadido por otros reinos."
      - ""
      - "Si invades un Reino, no podrás"
      - "volver al modo pacífico durante una semana."
      - ""
      - "&2Tiempo de Espera&8: &6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Escudo&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Compra un escudo para tu"
      - "reino para proteger tu reino"
      - "contra invasores."
    posx: 2
    posy: 1
  invites:
    name: "&6Invitaciones&8: %invites%"
    material: BOOK
    lore:
      - "&7Cuando está apagado, cualquiera puede"
      - "únirse a este reino sin necesidad"
      - "una invitación con &2/k join %kingdoms_name%"
    posx: 3
    posy: 1
  relations:
    name: "&6Relaciones"
    material: WRITABLE_BOOK
    lore:
      - "&7Cambia las relaciónes"
      - "con otros reinos."
    posx: 4
    posy: 1
  tax:
    name: "&6Impuestos"
    material: PAPER
    lore:
      - "&7Cambia los impuestos de tu reino"
      - "para los miembros."
      - ""
      - "&6Impuestos&8: &2$%kingdoms_fancy_tax%"
      - "&6Ecuacion&8: &2%tax_equation%"
      - ""
      - "&6Impuesto de facturación&8: &2$%kingdoms_fancy_kingdom_tax%"
    posx: 5
    posy: 1
  public-home:
    name: "&6Casa Publica&8: &2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&7Puedes hacer tu casa"
      - "público para que otros jugadores puedan visitar"
      - "utilizando el comando &6/k home %kingdoms_name%&7."
    posx: 6
    posy: 1
  flag:
    name: "&6Bandera"
    material: BLACK_BANNER
    lore:
      - "&7Establece la bandera de tu reino para Dynmap."
      - "Click para ver la URL de su bandera."
      - "Esto no actualizará el mapa al instante."
    posx: 7
    posy: 1
  color:
    name: "&6Color&8: &c%r%&7, &2%g%&7, &9%b% &7(&d%hex%&7)"
    material: BLACK_DYE
    lore:
      - "&7Establece el marcador de color de"
      - "tu reino para Dynmap."
      - "Esto no actualizará el mapa al instante."
    posx: 8
    posy: 1

  back:
    name: "&2Volver"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Volver al menu de la central."
    posx: 9
    posy: 1