main: ${project.groupId}.main.${project.name}
name: ${project.name}
description: ${project.description}
author: Crypto Morin
version: ${project.version}
api-version: "1.13"
softdepend: [ Citizens, MyPet, PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard, WorldEdit, Vault, AuthMe, DiscordSRV, LuckPerms,
              MythicMobs, Multiverse-Core, dynmap, Regionerator ]

# Since plugin command name is custom, it's handled internally.

permissions:
  kingdoms.debug:
    description: Show debug messages.
    default: op

  kingdoms.updates:
    description: Checks for updates on join.
    default: op

  kingdoms.command.about:
    default: true

  kingdoms.command.outpost.join:
    default: true

  kingdoms.command.outpost.teleport:
    default: true

  kingdoms.command.outpost.start:
    default: op

  kingdoms.command.outpost.create:
    default: op

  kingdoms.command.outpost.stop:
    default: op

  kingdoms.command.outpost.remove:
    default: op

  kingdoms.command.outpost.center:
    default: op

  kingdoms.command.outpost.spawn:
    default: op

  kingdoms.command.top:
    default: true

  kingdoms.command.home:
    description: Teleport to kingdoms home.
    default: true

  kingdoms.command.home.bypass.timer:
    description: Instantly teleprot.
    default: op

  kingdoms.command.home.others:
    description: Teleport to other kingdoms home.
    default: op

  kingdoms.command.nation:
    default: true

  kingdoms.command.nation.spawn:
    default: true

  kingdoms.command.nation.setspawn:
    default: true

  kingdoms.command.admin.dynmap:
    default: op

  kingdoms.command.nation.nexus:
    default: true

  kingdoms.command.nation.bank:
    default: true

  kingdoms.command.nation.create:
    default: true

  kingdoms.command.nation.kick:
    default: true

  kingdoms.command.nation.rename:
    default: true

  kingdoms.command.nation.show:
    default: true

  kingdoms.command.nation.top:
    default: true

  kingdoms.command.nation.leave:
    default: true

  kingdoms.command.nation.disband:
    default: true

  kingdoms.command.nation.broadcast:
    default: true

  kingdoms.command.nation.unsetspawn:
    default: true

  kingdoms.command.nation.capital:
    default: true

  kingdoms.command.nation.demote:
    default: true

  kingdoms.command.nation.promote:
    default: true

  kingdoms.command.nation.invite:
    default: true

  kingdoms.command.nation.accept:
    default: true

  kingdoms.command.nation.decline:
    default: true

  kingdoms.command.nation.join:
    default: true

  kingdoms.protection-signs.use:
    default: true

  kingdoms.protection-signs.use.creative:
    default: true

  kingdoms.protection-signs.open:
    default: op

  kingdoms.protection-signs.break:
    default: op

  kingdoms.command.sell:
    default: true

  kingdoms.command.pvp:
    default: true

  kingdoms.command.fly:
    default: true

  kingdoms.command.bank:
    default: true

  kingdoms.command.tradable:
    default: true

  kingdoms.command.join:
    default: true

  kingdoms.command.resourcepoints:
    default: true

  kingdoms.command.bypass.timer:
    description: Bypasses the timer before teleporting.
    default: false

  kingdoms.command.sethome:
    description: Set kingdom's home.
    default: true

  kingdoms.command.updates:
    description: Checks for updates.
    default: op

  kingdoms.command.donate:
    default: true

  kingdoms.creative.pickup:
    default: op

  kingdoms.command.help:
    description: Accesss to help command.
    default: true

  kingdoms.command.claim:
    default: true

  kingdoms.command.claim.auto:
    default: true

  kingdoms.command.claim.chunk:
    default: true

  kingdoms.command.claim.full:
    default: true

  kingdoms.command.nexus:
    default: true

  kingdoms.command.unsethome:
    default: true

  kingdoms.command.kick:
    default: true

  kingdoms.command.promote:
    default: true

  kingdoms.command.demote:
    default: true

  kingdoms.command.invite:
    default: true

  kingdoms.chat.colors:
    default: op

  kingdoms.silent.leave:
    default: false

  kingdoms.silent.join:
    default: false

  kingdoms.flight.damage:
    default: op

  kingdoms.flight.lands:
    default: op

  kingdoms.flight.nearby-enemies:
    default: op

  kingdoms.command.visualize:
    default: true

  kingdoms.command.visualize.permanent:
    default: true

  kingdoms.command.visualize.details:
    description: Show detailed description of the land.
    default: op

  kingdoms.command.admin.land:
    default: op

  kingdoms.command.admin.player:
    default: op

  kingdoms.command.tag:
    default: true

  kingdoms.command.invites:
    default: true

  kingdoms.command.ally:
    default: true

  kingdoms.command.revoke:
    default: true

  kingdoms.command.truce:
    default: true

  kingdoms.command.enemy:
    default: true

  kingdoms.command.relations:
    default: true

  kingdoms.command.accept:
    default: true

  kingdoms.command.decline:
    default: true

  kingdoms.command.teleport:
    default: true

  kingdoms.command.invade:
    default: true

  kingdoms.command.surrender:
    default: true

  kingdoms.command.leave:
    default: true

  kingdoms.command.chat:
    default: true

  kingdoms.command.map:
    default: true

  kingdoms.command.map.auto:
    default: true

  kingdoms.command.disband:
    default: true

  kingdoms.command.king:
    default: true

  kingdoms.command.unclaimall:
    default: true

  kingdoms.command.undo:
    default: true

  kingdoms.command.unclaim:
    description: Unclaim kingdom's lands.
    default: true

  kingdoms.command.create:
    description: Creates a new Kingdom.
    default: true

  kingdoms.command.lore:
    default: true

  kingdoms.command.show:
    description: Shows a Kingdom's information.
    default: true

  kingdoms.command.show.others:
    description: Show other kingdoms info.
    default: true

  kingdoms.command.admin.toggle:
    default: op

  kingdoms.command.show.admin:
    description: Shows the admin kingdom info.
    default: op

  kingdoms.command.rename:
    description: Rename your kingdom.
    default: true