main: org.kingdoms.main.Kingdoms
name: Kingdoms
description: ${project.description}
author: Crypto Morin
version: ${project.version}
api-version: "1.13"
softdepend: [ Citizens, MyPet, PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard, WorldEdit, Vault, AuthMe, DiscordSRV, LuckPerms,
              MythicMobs, Multiverse-Core, dynmap, BlueMap, Regionerator,
  # Vanish:
              Essentials, CMI ]

# Since plugin command name is custom, it's handled internally.
permissions:
  kingdoms.commands.bypass.cooldown.<command>:
    default: op

  kingdoms.commands.bypass.disabled-worlds.<command>:
    default: op

  kingdoms.markers.*:
    default: true