title: "&cUstawienia Mapy"
type: HOPPER

options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      &7Pokazuje mapę królestwa jako tablicę wyników,
      co jest znacznie bardziej wygodne niż
      tryb automatycznej mapy i aktualizuje się automatycznie.

      Wadą jest to, że
      zajmuje ogromną część ekranu,
      a musisz zapamiętać symbole oraz
      kolory i ich znaczenie.

      Ta opcja resetuje się po opuszczeniu.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Przełącz Tablicę Wyników"
      glow: true
    else:
      name: "{$disabled} Przełącz Tablicę Wyników"
    reset:
      slot: 1
      material: PLAYER_HEAD
      name: '&4Zresetuj Ustawienia'

    # https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '&2Zmień Rozmiar'
    lore:
      - "&7Zmień &aszerokość &7i &awysokość &7swojej mapy"
      - "&7Twój obecny rozmiar&8: &2%kingdoms_map_width%&7, &2%kingdoms_map_height%"

    # https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmZiZGYzZjE4NzA4OTQzNTIwNDhkZmVjZDk2Mjg0NmRlYTg5M2IyMTU0Yzg1In19fQ=='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "&7Mapa pojawia się automatycznie"
      - "podczas przemieszczania się po różnych ziemiach."

    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} Auto"
      # https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} Auto"
      # https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmY3OTMzZWE0M2FjOGVmMmZkNzBkZWZkYyJ9fX0='
  gui:
    slot: 4
    material: CHEST
    name: "&2Zobacz mapę w interfejsie GUI"
    lore: |
      &7Zalety to lepsze zachowanie
      po kliknięciu i bardziej czytelne
      ikony dla różnych ziem.

      Wady to ograniczenie rozmiaru
      inwentarza GUI i ograniczenie mobilności.
