title: "&8-=( &7Настройки &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Пацифизм&8: %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7Пока вы пацифисты,"
      - "ваше королевство не может вторгаться"
      - "в другие королевства, но они не могут вторгаться к вам."
      - ""
      - "Если вы вторгнитесь в королевство, вы не"
      - "сможете включить пацифизм неделю."
    posx: 1
    posy: 1
  shields:
    name: "&6Щит&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Купите щит для Вашего"
      - "королевства, что бы защитить его от"
      - "вторжений."
    posx: 2
    posy: 1
  invites:
    name: "&6Приглашения&8: %invites%"
    material: BOOK
    lore:
      - "&7Когда выключено, каждый может"
      - "присоединиться к этому королевству"
      - "без необходимости приглашения"
      - "используя &2/k nation join %kingdoms_nation%"
    posx: 3
    posy: 1
  relations:
    name: "&6Отношения"
    material: WRITABLE_BOOK
    lore:
      - "&7Измените свои атрибуты отношений для"
      - "других королевств."
    posx: 4
    posy: 1
  tax:
    name: "&6Плата"
    material: PAPER
    lore:
      - "&7Измените плату для членов"
      - "Вашего королевства."
      - ""
      - "&6Плата&8: &2$%kingdoms_fancy_tax%"
      - "&6Уравнение&8: &2%tax_equation%"
      - ""
      - "&6Налог&8: &2$%kingdoms_fancy_kingdom_tax%"
    posx: 5
    posy: 1

  back:
    name: "&2Вернуться"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Вернуться в меню Нексуса."
    posx: 9
    posy: 1
