title: str
rows: int # Range handled internally
sound: Sound
interactable: List
disallow-creative: bool
message: str

options:
  (values):
    name: str
    material: Material
    lore: str
    can-take: bool
    condition: str
    sound: Sound
    message: str
    amount: int
    # Slot ranges are handled internally.
    slot: int
    posx: int
    posy: int
    slots:
      (type): list
      (elements): int