title: "&8-=( &7Settings &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Pacifism&8: %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7When you're in pacifism mode,"
      - "your kingdom cannot invade"
      - "and cannot be invaded by other kingdoms."
      - ""
      - "If you invade a Kingdom, you cannot go"
      - "back into pacifism mode for a week."
      - ""
      - "&2Cooldown&8: &6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Shield&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Buy a shield for your"
      - "kingdom to protect your kingdom"
      - "against invades."
    posx: 2
    posy: 1
  invites:
    name: "&6Invites&8: %invites%"
    material: BOOK
    lore:
      - "&7When turned off, anyone can"
      - "join this kingdom without needing"
      - "an invitation with &2/k join %kingdoms_name%"
    posx: 3
    posy: 1
  relations:
    name: "&6Relations"
    material: WRITABLE_BOOK
    lore:
      - "&7Change your relation attributes"
      - "for other kingdoms."
    posx: 4
    posy: 1
  tax:
    name: "&6Tax"
    material: PAPER
    lore:
      - "&7Change your kingdom taxes"
      - "for members."
      - ""
      - "&6Tax&8: &2$%kingdoms_fancy_tax%"
      - "&6Equation&8: &2%tax_equation%"
      - ""
      - "&6Billing Tax&8: &2$%kingdoms_fancy_kingdom_tax%"
    posx: 5
    posy: 1
  public-home:
    name: "&6Public Home&8: &2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&7You can make your home"
      - "public so other players can visit"
      - "using &6/k home %kingdoms_name% &7command."
    posx: 6
    posy: 1
  flag:
    name: "&6Kingdom Flag"
    material: BLACK_BANNER
    lore:
      - "&7Set your kingdom flag for Dynmap."
      - "&7Click to see your flag URL."
    posx: 7
    posy: 1
  color:
    name: "&6Kingdom Color&8: &c%r%&7, &2%g%&7, &9%b% &7(&d%hex%&7)"
    material: BLACK_DYE
    lore:
      - "&7Set your kingdom marker"
      - "color for Dynmap."
    posx: 8
    posy: 1

  back:
    name: "&2Back"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Go back to nexus menu."
    posx: 9
    posy: 1