title: "&8-=( &7Ayarlar &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Kalkan&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Ulusunu korumak için ulusun"
      - "için bir kalkan satın al."
    posx: 1
    posy: 1
  invites:
    name: "&6Davetler&8: %invites%"
    material: BOOK
    lore:
      - "&7Kapatıldığında, &2/k nation join %kingdoms_nation% &7ile "
      - "herhangi bir davetiyeye ihtiyaç"
      - "duymadan bu ulusa herkes katılabilir."
    posx: 2
    posy: 1
  relations:
    name: "&6İlişkiler"
    material: WRITABLE_BOOK
    lore:
      - "&7Diğer uluslar için ilişki "
      - "niteliklerinizi değiştirin."
    posx: 3
    posy: 1
  tax:
    name: "&6Vergi"
    material: PAPER
    lore:
      - "&7Krallıklar için ulus "
      - "vergilerinizi değiştirin."
      - ""
      - "&6Vergi&8: &2$%kingdoms_fancy_nation_tax%"
      - "&6Denklem&8: &2%tax_equation%"
      - ""
      - "&6Fatura Vergisi&8: &2$%kingdoms_fancy_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Geri Dön"
    material: PLAYER_HEAD
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Nexus menüsüne geri dönün."
    posx: 9
    posy: 1