title: "{$sep}-=( &7Beállítások {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '&2Vissza'
    lore: [ '&6Vissza a nexus menübe.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 4
    posy: 1
    material: DARK_OAK_DOOR
    name: "{$s}Nyilvános otthon{$colon} %kingdoms_bool_kingdom_home_is_public%"
    lore: |
      &7Amikor nyilvános az otthonod,
      bárki odateleportálhat használva
      a {$p}/k home %kingdoms_kingdom_name%
      &7parancsot.
  hidden:
    posx: 5
    posy: 1
    material: POTION
    color: 818595
    name: "{$s}Rejtett{$colon} %kingdoms_bool_kingdom_is_hidden%"
    lore: |
      &7Rejtett királyság nem látszódik
      a {$p}/k map &7parancsnál és az
      online térképeken.
  tax:
    posx: 6
    posy: 1
    material: PAPER
    name: '&6Adó'
    lore: |
      &7Királyságod adóinak
      változtatása a tagok
      számára.

      &6Tagság adóegyenlete{$colon}
      &2%tax_equation%
      &6Tagjaidnak adója{$colon} &2$%fancy@kingdoms_tax%

      &6Királyság kiszólgáló adó{$colon} &2$%fancy@kingdoms_kingdom_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '&6Kapcsolatok'
    lore: |
      &7Királyságodnak a kapcsolati
      attribútumainak változtatása
      más királyságok számára.

      {$sep}[&e!{$sep}] {$es}Egyes attribútumok működéséhez
      mindkét királyságban szükséges
      engedélyezni az attribútumokat
      a kapcsolathoz.

      Például ha a {$e}BUILD {$es}attribútum
      engedélyezve van a szövetségesek
      számára, de egy olyan szövetséges
      földjére próbálsz építeni, akinél
      nincs engedélyezve a {$e}BUILD
      {$es}attribútum a szövetségeseinek,
      ez nem fog működni. Nem fognak tudni
      a területeden építeni.
  flag:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '&6Zászló'
    lore: |
      &7Állítsd be a királyságod zászlóját
      az online térképekhez. Klikk a zászló
      URL-jének megtekintéséhez.
      Ez nem frissíti azonnal a térképet.
  pacifism:
    posx: 7
    posy: 3
    material: END_CRYSTAL
    name: '&6Békés{$colon} %kingdoms_bool_kingdom_is_pacifist%'
    lore: |
      &7Amikor békés módban vagy, a
      királyságod nem támadhat és
      nem is támadhatják meg más
      királyságok.

      Ha megostromolsz egy királyságot,
      akkor egy hétig nem válthatsz
      vissza békés módba.

      &2Hátralévő idő{$colon} &6%pacifism_cooldown%
  invites:
    posx: 3
    posy: 5
    material: BOOK
    name: '&6Meghívás szükséges{$colon} %kingdoms_bool_kingdom_requires_invite%'
    lore: |
      &7Amikor ki van kapcsolva akkor bárki
      meghívás nélkül is tud csatlakozni
      ehhez a királyságodhoz, használva a
      {$p}/k join %kingdoms_kingdom_name%
      &7parancsot.
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '&6Szín{$colon} &c%r%&7, &2%g%&7, &9%b% &7(%hex@kingdoms_kingdom_color%%kingdoms_kingdom_color%&7)'
    lore: |
      &7Állítsd be a királyságod
      jelölőszínét a csevegéshez
      és az online földtérképekhez.
  shields:
    posx: 7
    posy: 5
    material: SHIELD
    name: '&6Pajzs{$colon} &2%time@kingdoms_shield_time_left%'
    lore: |
      &7Vásárolj pajzsot a
      királyságodnak, hogy
      megvédd az ostromok ellen.
