title: "{$sep}-=( &7Ayarlar {$sep})=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Kalkan{$colon} &2%time@kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Ulusunu korumak için ulusun"
      - "için bir kalkan satın al."
    posx: 1
    posy: 1
  invites:
    name: "&6Davetler{$colon} %invites%"
    material: BOOK
    lore:
      - "&7Kapatıldığında, &2/k nation join %kingdoms_nation_name% &7ile "
      - "herhangi bir davetiyeye ihtiyaç"
      - "duymadan bu ulusa herkes katılabilir."
    posx: 2
    posy: 1
  relations:
    name: "&6İlişkiler"
    material: WRITABLE_BOOK
    lore:
      - "&7Diğer uluslar için ilişki "
      - "niteliklerinizi değiştirin."
    posx: 3
    posy: 1
  tax:
    name: "&6Vergi"
    material: PAPER
    lore:
      - "&7Krallıklar için ulus "
      - "vergilerinizi değiştirin."
      - ""
      - "&6Vergi{$colon} &2$%fancy@kingdoms_nation_tax%"
      - "&6Denklem{$colon} &2%tax_equation%"
      - ""
      - "&6Fatura Vergisi{$colon} &2$%fancy@kingdoms_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Geri Dön"
    material: PLAYER_HEAD
    skull: "{$gui-back}"
    lore:
      - "&6Nexus menüsüne geri dönün."
    posx: 9
    posy: 1