title: "&8-=( &7Beállítások &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Pacifizmus&8: %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7Amikor pacifista módban vagy,"
      - "a királyságod nem tud ostromolni és"
      - "nem lehet ostromolni."
      - ""
      - "Amennyiben megtámadsz egy másik királyságot"
      - "1 hétig nem tudsz pacifista módban váltani."
      - ""
      - "&2Hátralévő idő&8: &6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Pajzs&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Vásárolj pajzsot a királyságodnak,"
      - "hogy megvédjen az ostromok ellen."
    posx: 2
    posy: 1
  invites:
    name: "&6Meghívás&8: %invites%"
    material: BOOK
    lore:
      - "&7Amennyiben ez az opció ki van kapcsolva"
      - "bárki csatlakozhat a királysághoz meghívó"
      - "nélkül. Parancs: &2/k join %kingdoms_name%"
    posx: 3
    posy: 1
  relations:
    name: "&6Kapcsolatok"
    material: WRITABLE_BOOK
    lore:
      - "&7Állítsd be a jogokat más"
      - "királyságok részére."
    posx: 4
    posy: 1
  tax:
    name: "&6Adó"
    material: PAPER
    lore:
      - "&7Adók beállítása"
      - ""
      - "&6Tagok adója&8: &2$%kingdoms_fancy_tax%"
      - "&6Egyenlet&8: &2%tax_equation%"
      - ""
      - "&6Fizetendő&8: &2$%kingdoms_fancy_kingdom_tax%"
    posx: 5
    posy: 1
  public-home:
    name: "&6Publikus Otthon&8: &2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&7Publikussá teheted a királyságod"
      - "otthonát, így a többi játékos meglátogathatja."
      - "&6/k home %kingdoms_name% &7paranccsal."
    posx: 6
    posy: 1
  back:
    name: "&2Vissza"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Vissza a nexus menübe."
    posx: 9
    posy: 1