title: "&8-=(&7设置&8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6护盾&8:&2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7给你的文明买一个保护它免受侵略的护盾。"
    posx: 1
    posy: 1
  invites:
    name: "&6邀请&8:%invites%"
    material: BOOK
    lore:
      - "&7当关上时，任何人都无需邀请，只需要输入&2/k nation join %kingdoms_nation%即可加入"
    posx: 2
    posy: 1
  relations:
    name: "&6外交关系"
    material: WRITABLE_BOOK
    lore:
      - "&7改变你与其他文明的外交关系。"
    posx: 3
    posy: 1
  tax:
    name: "&6赋税"
    material: PAPER
    lore:
      - "&7改变你的文明收取成员国的税款。"
      - ""
      - "&6赋税&8:&2$%kingdoms_fancy_nation_tax%"
      - "&6税率&8:&2%tax_equation%"
      - ""
      - "&6税款&8: &2$%kingdoms_fancy_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2返回"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6返回到核心界面。"
    posx: 9
    posy: 1