title: "{$sep}-=({$p}设置{$sep})=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "{$s}护盾{$sep}:{$p}%kingdoms_time_shield_time_left%"
    material: SHIELD
    lore:
      - "{$p}给你的文明买一个保护它免受侵略的护盾。"
    posx: 1
    posy: 1
  invites:
    name: "{$s}邀请{$sep}:%invites%"
    material: BOOK
    lore:
      - "{$p}当关上时，任何人都无需邀请，只需要输入{$p}/k nation join %kingdoms_nation%即可加入"
    posx: 2
    posy: 1
  relations:
    name: "{$s}外交关系"
    material: WRITABLE_BOOK
    lore:
      - "{$p}改变你与其他文明的外交关系。"
    posx: 3
    posy: 1
  tax:
    name: "{$s}赋税"
    material: PAPER
    lore:
      - "{$p}改变你的文明收取成员国的税款。"
      - ""
      - "{$s}赋税{$sep}:{$p}$%kingdoms_fancy_nation_tax%"
      - "{$s}税率{$sep}:{$p}%tax_equation%"
      - ""
      - "{$s}税款{$sep}:{$p}$%kingdoms_fancy_server_nation_tax%"
    posx: 4
    posy: 1
  
  back:
    name: "{$p}返回"
    material: PLAYER_HEAD
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "{$s}返回到核心界面。"
    posx: 9
    posy: 1