title: "&cНалаштування Карти"
type: HOPPER

options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      &7Показує карту королівства як таблицю рахунку,
      яка є набагато зручнішою, ніж автоматичний режим карти і
      оновлюється автоматично.

      Недолік полягає в тому, що
      вона займає велику частину вашого екрану,
      і вам доведеться запам'ятати символи і
      кольори та їх значення.

      Ця опція скидається, якщо ви вийдете.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Увімкнути таблицю рахунку"
      glow: true
    else:
      name: "{$disabled} Увімкнути таблицю рахунку"
  reset:
    slot: 1
    material: PLAYER_HEAD
    name: '&4Скинути Налаштування'

    # https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '&2Змінити Розмір'
    lore:
      - "&7Змініть свою власну ширину та висоту карти"
      - "&7Ваш поточний розмір&8: &2%kingdoms_map_width%&7, &2%kingdoms_map_height%"

    # https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmFjZDg5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "&7Карта автоматично відображається,"
      - "коли ви рухаєтеся в різних місцях."

    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} Авто"
      # https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} Авто"
      # https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmвL3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmFmM2IyMTU0Yzg1In19fX0='
  gui:
    slot: 4
    material: CHEST
    name: "&2Подивіться карту в інтерфейсі"
    lore: |
      &7Переваги полягають в кращому
      поведінці під час натискання та
      чітких піктограмах для різних місць.

      Недоліги включають в себе
      обмеженість розміру інвентаря
      і обмеження вашої мобільності.
