title: "&8-=( &2Configurações do Campeão &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bAtualizar equipamento"
    material: DIAMOND_CHESTPLATE
    lore:
      - "&7Melhore seus campeões"
      - "armadura e arma a cada atualização."
      - ""
      - "&2Nível{$colon} &6%level%"
      - "&2Custo{$colon} &6%cost%"
    slot: 0
  change:
    name: "&6Mudar"
    material: DIAMOND_SWORD
    lore:
      - "&7Mude seu tipo de campeão."
    slot: 1

  back:
    name: "&2Voltar"
    material: BARRIER
    lore:
      - "&6Volte para as atualizações de campeão."
    slot: 4