title: "&8-=( &7Einstellungen &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Schild&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Kaufe ein Schild für dein"
      - "Königreich, um es gegen"
      - "Angreifer zu schützen."
    posx: 1
    posy: 1
  invites:
    name: "&6Einladungen&8: %invites%"
    material: BOOK
    lore:
      - "&7Wenn es deaktiviert ist,"
      - "kann jeder das Königreich mit"
      - "&2/k nation join %kingdoms_nation% &7beitreten."
    posx: 2
    posy: 1
  relations:
    name: "&6Beziehungen"
    material: WRITABLE_BOOK
    lore:
      - "&7Ändere den Beziehungs-Status"
      - "zu anderen Königreichen."
    posx: 3
    posy: 1
  tax:
    name: "&6Steuer"
    material: PAPER
    lore:
      - "&7Ändere die königlichen Steuern"
      - "für Mitglieder."
      - ""
      - "&6Steuer&8: &2$%kingdoms_fancy_nation_tax%"
      - "&6Gleichung&8: &2%tax_equation%"
      - ""
      - "&6Abrechnungssteuer&8: &2$%kingdoms_fancy_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Zurück"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Gehe zurück zum Nexus-Menü."
    posx: 9
    posy: 1