title: "{$sep}-=({$p}斗士{$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&b升级装备"
    material: DIAMOND_CHESTPLATE

    lore:
      - "{$p}每次升级都会"
      - "加强斗士的护甲和武器。"
      - ""
      - "{$p}等级{$sep}:{$s}%level%"
      - "{$p}价格{$sep}:{$s}%cost%"
    slot: 0
  change:
    name: "{$s}更改"
    material: DIAMOND_SWORD
    lore:
      - "{$p}更改你的斗士类型。"
    slot: 1

  back:
    name: "{$p}返回"
    material: BARRIER
    lore:
      - "{$s}返回到斗士升级界面。"
    slot: 4