title: "&8-=( &2Şampiyon Ayarları &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bEkipmanı Yükselt"
    material: DIAMOND_CHESTPLATE
    sounds:
      max-level: BLOCK_NOTE_BLOCK_BASS
      not-enough-resource-points: BLOCK_NOTE_BLOCK_BASS
      upgraded: ENTITY_EXPERIENCE_ORB_PICKUP
    lore:
      - "&7Her yükseltme ile şampiyonunuzun"
      - "zırhını ve silahını geliştirin."
      - ""
      - "&2Seviye&8: &6%level%"
      - "&2Maliyet&8: &6%cost%"
    slot: 0
  change:
    name: "&6Değiştir"
    material: DIAMOND_SWORD
    lore:
      - "&7Şampiyon türünü değiştirin."
    slot: 1

  back:
    name: "&2Geri Dön"
    material: BARRIER
    lore:
      - "&6Şampiyon yükseltmelerine geri dönün."
    slot: 4