title: "{$sep}-=( &7Beállítások {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '&2Vissza'
    lore: [ '&6Vissza a nexus menübe.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 3
    posy: 5
    material: DARK_OAK_DOOR
    name: "{$s}Nyilvános otthon{$colon} %kingdoms_bool_nation_home_is_public%"
    lore: |
      &7Amikor nyilvános az otthonod,
      bárki odateleportálhat használva
      a {$p}/k nation home %kingdoms_nation_name%
      &7parancsot.
  tax:
    posx: 7
    posy: 5
    material: PAPER
    name: '&6Adó'
    lore: |
      &7Nemzetednek az adóinak
      változtatása a tagok számára.

      &6Tagság adóegyenlet{$colon}
      &2%tax_equation%
      &6Tagjaidnak adója{$colon} &2$%fancy@kingdoms_nation_tax%

      &6Nemzet kiszólgáló adó{$colon} &2$%fancy@kingdoms_nation_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '&6Kapcsolatok'
    lore: |
      &7Nemzetednek a kapcsolati attribútumainak
      változtatása más nemzetek számára.

      {$sep}[&e!{$sep}] {$es}Egyes attribútumok
      működéséhez mindkét királyságban
      szükséges engedélyezni az attribútumokat
      a kapcsolathoz.

      Például ha a {$e}BUILD {$es}attribútum
      engedélyezve van a szövetségesek
      számára, de egy olyan szövetséges
      földjére próbálsz építeni, akinél
      nincs engedélyezve a {$e}BUILD
      {$es}attribútum a szövetségeseinek,
      ez nem fog működni. Nem fognak tudni
      a területeden építeni.
  flag:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '&6Zászló'
    lore: |
      &7Állítsd be a nemzeted zászlóját az
      online térképekhez. Klikk a zászló
      URL-jének megtekintéséhez.
      Ez nem frissíti azonnal a térképet.
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '&6Szín{$colon} &c%r%&7, &2%g%&7, &9%b% &7(%hex@kingdoms_nation_color%%kingdoms_nation_color%&7)'
    lore: |
      &7Állítsd be a nemzeted
      jelölőszínét a csevegéshez
      és az online földtérképekhez.
  shields:
    posx: 7
    posy: 3
    material: SHIELD
    name: '&6Pajzs{$colon} &2%time@kingdoms_nation_shield_time_left%'
    lore: |
      &7Vásárolj pajzsot a nemzeted
      védelmére, hogy megvédd az
      ostromok ellen a királyságodat.

      Azok a királysági tagok, akik
      akkor támadnak, amikor a nemzet
      pajzsai engedélyezve vannak,
      átmenetileg elveszítik a nemzet
      pajzsához való hozzáférést.
