title: "{$sep}-=( &2Bajnok beállításai {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bFelszerelés fejlesztése"
    material: DIAMOND_CHESTPLATE
    lore:
      - "&7A fejlesztés tökéletesíti a"
      - "bajnokod páncélját és fegyverét."
      - ""
      - "&2Szint{$colon} &6%level%"
      - "&2Költség{$colon} &6%cost%"
    slot: 0
  change:
    name: "&6Csere"
    material: DIAMOND_SWORD
    lore:
      - "&7A bajnok típusának cseréje."
    slot: 1

  back:
    name: "&2Vissza"
    material: BARRIER
    lore:
      - "&6Vissza a bajnok fejlesztéséhez."
    slot: 4