title: "&8-=( &2A Bajnok beállításai &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bFelszerelés fejlesztése"
    material: DIAMOND_CHESTPLATE
    sounds:
      max-level: BLOCK_NOTE_BLOCK_BASS
      not-enough-resource-points: BLOCK_NOTE_BLOCK_BASS
      upgraded: ENTITY_EXPERIENCE_ORB_PICKUP
    lore:
      - "&7A fejlesztés tökéletesíti a"
      - "bajnokod páncélját és fegyverét."
      - ""
      - "&2Szint&8: &6%level%"
      - "&2Költség&8: &6%cost%"
    slot: 0
  change:
    name: "&6Csere"
    material: DIAMOND_SWORD
    lore:
      - "&7A bajnok típusának cseréje."
    slot: 1

  back:
    name: "&2Vissza"
    material: BARRIER
    lore:
      - "&6Vissza a bajnok fejlesztéséhez."
    slot: 4