title: "{$sep}-=( &7Ayarlar {$sep})=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Barışçıl{$colon} %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&7Barışçıl modundayken, krallığınız"
      - "başka krallıklar tarafından istila"
      - "edilemez ve istila edilemez."
      - ""
      - "Bir Krallığı işgal ederseniz, bir hafta boyunca "
      - "barışçıl moduna geri dönemezsiniz."
      - ""
      - "&2Bekleme Süresi{$colon} &6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Kalkan{$colon} &2%time@kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Krallığınızı istilalara karşı"
      - "korumak için krallığınız için"
      - "bir kalkan satın alın."
    posx: 2
    posy: 1
  invites:
    name: "&6Davetler{$colon} %invites%"
    material: BOOK
    lore:
      - "&7Kapatıldığında, &2/k join %kingdoms_kingdom_name% &7ile"
      - "herhangi bir davetiyeye ihtiyaç duymadan"
      - "herkes bu krallığa katılabilir."
    posx: 3
    posy: 1
  relations:
    name: "&6İlişkiler"
    material: WRITABLE_BOOK
    lore:
      - "&7Diğer krallıklar için ilişki"
      - "niteliklerinizi değiştirin."
    posx: 4
    posy: 1
  tax:
    name: "&6Vergi"
    material: PAPER
    lore:
      - "&7Üyeler için krallık vergilerinizi"
      - "değiştirin."
      - ""
      - "&6Vergi{$colon} &2$%fancy@kingdoms_tax%"
      - "&6Denklem{$colon} &2%tax_equation%"
      - ""
      - "&6Fatura Vergisi{$colon} &2$%fancy@kingdoms_kingdom_tax%"
    posx: 5
    posy: 1
  public-home:
    name: "&6Public Home{$colon} &2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&6/k home %kingdoms_kingdom_name% &7komutunu"
      - "kullanarak diğer oyuncuların ziyaret"
      - "edebilmesi için evinizi herkese açık hale getirebilirsiniz."
    posx: 6
    posy: 1
  flag:
    name: "&6Bayrak"
    material: BLACK_BANNER
    lore:
      - "&7Dynmap için krallık bayrağınızı ayarlayın."
      - "Bayrak URL'nizi görmek için tıklayın."
      - "Bu, haritayı anında güncellemeyecektir."
    posx: 7
    posy: 1
  color:
    name: "&6Renk{$colon} &c%r%&7, &2%g%&7, &9%b% &7(&d%hex%&7)"
    material: BLACK_DYE
    lore:
      - "&7Dynmap için krallık işaretleyici(markers)"
      - "renginizi ayarlayın."
      - "Bu, haritayı anında güncellemeyecektir."
    posx: 8
    posy: 1

  back:
    name: "&2Geri Dön"
    material: PLAYER_HEAD
    skull: "{$gui-back}"
    lore:
      - "&6Nexus menüsüne geri dönün."
    posx: 9
    posy: 1