title: "&8Настройка"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    name: "&6Пацифизм&8: %pacifism%"
    material: END_CRYSTAL
    lore:
      - "&8▪ &7Когда вы находитесь в режиме"
      - "пацифизма, ваше королевство не может"
      - "вторгнуться и не может быть"
      - "захвачено другими королевствами"
      - ""
      - "&4&l! &cЕсли вы вторглись в королевство, вы не сможете"
      - "вернуться в режим пацифизма в течение недели."
      - ""
      - "&8▪ &9КУЛДАУН&8: &b%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Щит&8: &b%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&8▪ &7Купите щит для своего"
      - "королевства чтобы защитить"
      - "его от вторжений"
    posx: 2
    posy: 1
  invites:
    name: "&6Приглашения&8: %invites%"
    material: BOOK
    lore:
      - "&8▪ &7Если этот параметр отключен, любой может"
      - "присоединиться к этому королевству без"
      - "приглашения с помощью &e/k join %kingdoms_kingdom_name%"
    posx: 3
    posy: 1
  relations:
    name: "&6Отношения"
    material: WRITABLE_BOOK
    lore:
      - "&8▪ &7Измените свои атрибуты отношений"
      - "для других королевств"
    posx: 4
    posy: 1
  tax:
    name: "&6Налоги"
    material: PAPER
    lore:
      - "&8▪ &7Измените уравление налогов "
      - "для ваших жителей"
      - ""
      - "&8▪ &7Твой налог&8: &e%kingdoms_fancy_tax% монет"
      - "&8▪ &dУравнение&8: &9%tax_equation%"
      - ""
      - "&8▪ &7Налог для вашего королевства&8: "
      - " &e%kingdoms_fancy_kingdom_tax% монет"
      - ""
      - " &bНажмите, чтобы установить &dуравнение&7"
      - " "
      - "  Пример: &e(money) * 5 / 100&7 ->"
      - "   забрать &a5%&7 из баланса игрока"
      - " "
      - "  &8(&bmoney&7 это баланс игрока&8)"
    posx: 5
    posy: 1
  public-home:
    name: "&6Публичность&8: &2%public_home%"
    material: DARK_OAK_DOOR
    lore:
      - "&8▪ &7Вы можете сделать свой дом"
      - "общедоступным, чтобы"
      - "другие игроки могли "
      - "посещать его с помощью"
      - "&e/k home %kingdoms_kingdom_name%"
    posx: 6
    posy: 1
  flag:
    name: "&6Знамя"
    material: BLACK_BANNER
    lore:
      - "&8▪ &7Изменить своё знамя на онлайн-карте"
      - "Нажмите и вставьте URL-ссылку"
      - "Это не обновит карту мгновенно"
    posx: 7
    posy: 1
  color:
    name: "&6Цвет&8: &c%r%&7, &2%g%&7, &9%b% &8[&aHEX: &d%hex%&8]"
    material: BLACK_DYE
    lore:
      - "&8▪ &7Установите цвет маркера "
      - "вашего королевства для онлайн-карты."
      - "Это не обновит карту мгновенно"
    posx: 8
    posy: 1

  back:
    name: "&cНазад"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - ""
    posx: 9
    posy: 1