title: "&8-=( &7Beállítások &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  pacifism:
    disabled:
      condition: kingdoms_pacifist
      name: "&2Békés &6módban vagy."
      material: END_CRYSTAL
      lore:       
        - "&7Amikor a királyságod békés akkor"
        - "a királyságod nem ostromolhat és más"
        - "királyságok nem ostromolhatják."
        - ""
        - "Ha megostromolsz egy királyságot akkor"
        - "egy hétig nem válthasz vissza békés módba."
        - ""
        - "&2Hátralevő idő&8: &6%pacifism_cooldown%"
    else:
      name: "&cAgresszor &6módban vagy."
      material: END_CRYSTAL
      lore:       
        - "&7Amikor a királyságod békés akkor"
        - "a királyságod nem ostromolhat és más"
        - "királyságok nem ostromolhatják."
        - ""
        - "Ha megostromolsz egy királyságot akkor"
        - "egy hétig nem válthasz vissza békés módba."
        - ""
        - "&2Hátralevő idő&8: &6%pacifism_cooldown%"
    posx: 1
    posy: 1
  shields:
    name: "&6Pajzs&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Vásárolj pajzsot a királyságodnak,"
      - "hogy megvédjen az ostromok ellen."
    posx: 2
    posy: 1
  invites:
    name: "&6Meghívás&8: %invites%"
    material: BOOK
    lore:
      - "&7Amikor ki van kapcsolva (&cDisabled&7) akkor"
      - "meghívás nélkül is lehet csatlakozni a"
      - "királyságodhoz a következő paranccsal:"
      - "&2/k join %kingdoms_name%"
    posx: 3
    posy: 1
  relations:
    name: "&6Kapcsolatok"
    material: WRITABLE_BOOK
    lore:
      - "&7Más királyságokkal való kapcsolati"
      - "attribútumok megváltoztatása."
    posx: 4
    posy: 1
  tax:
    name: "&6Adó"
    material: PAPER
    lore:
      - "&7A királyság tagjainak"
      - "adóinak módosítása."    
      - ""
      - "&6Adó&8: &2$%kingdoms_fancy_tax%"
      - "&6Egyenlet&8: &2%tax_equation%"
      - ""
      - "&6Számlázott adó&8: &2$%kingdoms_fancy_kingdom_tax%"
    posx: 5
    posy: 1
  public-home:
    true:
      condition: public_home
      name: "&cNyilvános &6az otthonod!"
      material: DARK_OAK_DOOR
      lore:
        - "&7Nyilvánossá teheted az otthonodat,"
        - "hogy más játékosok meg tudják látogatni"
        - "a &6/k home %kingdoms_name%"
        - "&7parancsot használva."
    else:
      name: "&2Nem nyilvános &6az otthonod!"
      material: DARK_OAK_DOOR
      lore:
        - "&7Nyilvánossá teheted az otthonodat,"
        - "hogy más játékosok meg tudják látogatni"
        - "a &6/k home %kingdoms_name%"
        - "&7parancsot használva."
    posx: 6
    posy: 1

  flag:
    name: "&6Zászló"
    material: BLACK_BANNER
    lore:
      - "&7A királyság zászlójának beállítása a"
      - "Dynmap-hoz. Klikk a zászlód URL-jére a"
      - "megtekintéséhez. Nem frissíti a térképet!"
    posx: 7
    posy: 1
  color:
    name: "&6Szín&8: &c%r%&7, &2%g%&7, &9%b% &7(&d%hex%&7)"
    material: BLACK_DYE
    lore:
      - "&7A királyság jelölőszínének beállítása"
      - "a Dynmap számára."
      - "Nem frissíti a térképet!"
    posx: 8
    posy: 1

  back:
    name: "&2Vissza"
    material: PLAYER_HEAD
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Vissza a Nexus menübe."
    posx: 9
    posy: 1