title: "&cConfigurações do mapa"
type: HOPPER

options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      &7Mostra o mapa do reino como um placar
      o que é muito mais conveniente do que
      modo de mapa automático e atualizações automaticamente.

      A desvantagem é que
      ocupa uma grande parte da sua tela
      e você deve memorizar os símbolos e
      cores e o que elas significam.

      Esta opção é redefinida se você sair.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Alternar Scoreboard"
      glow: true
    else:
      name: "{$disabled} Alternar Scoreboard"
  reset:
    slot: 1
    material: PLAYER_HEAD
    name: '&4Redefinir as configurações'

    # https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '&2Redimensionar'
    lore:
      - "&7Redimensione seu próprio mapa &alargura &7e &aaltura"
      - "&7Seu tamanho atual{$colon} &2%kingdoms_map_width%&7, &2%kingdoms_map_height%"

    # https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmZiZGYzZjE4NzA4OTQzNTIwNDhkZmVjZDk2Mjg0NmRlYTg5M2IyMTU0Yzg1In19fQ=='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "&7O mapa continua aparecendo automaticamente"
      - "enquanto você caminha para terras diferentes."

    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} auto"
      # https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} auto"
      # https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmY3OTMzZWE0M2FjOGVmMmZkNzBkZWZkYyJ9fX0='
  gui:
    slot: 4
    material: CHEST
    name: "&2Veja o mapa em uma GUI"
    lore: |
      &7As vantagens seriam melhores
      comportamento de clique e mais claro
      ícones para diferentes terras.

      As desvantagens seriam
      limite do tamanho do inventário da GUI
      e limitando sua mobilidade.