title: "{$sep}-=( &2Şampiyon Ayarları {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bEkipmanı Yükselt"
    material: DIAMOND_CHESTPLATE

    lore:
      - "&7Her yükseltme ile şampiyonunuzun"
      - "zırhını ve silahını geliştirin."
      - ""
      - "&2Seviye{$colon} &6%level%"
      - "&2Maliyet{$colon} &6%cost%"
    slot: 0
  change:
    name: "&6Değiştir"
    material: DIAMOND_SWORD
    lore:
      - "&7Şampiyon türünü değiştirin."
    slot: 1

  back:
    name: "&2Geri Dön"
    material: BARRIER
    lore:
      - "&6Şampiyon yükseltmelerine geri dönün."
    slot: 4