title: "{$sep}-=( &2Ustawienia Bohatera {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bUlepsz Wyposażenie"
    material: DIAMOND_CHESTPLATE
    lore:
      - "&7Ulepsz pancerz i broń swojego bohatera"
      - "za każdym razem, gdy dokonujesz ulepszenia."
      - ""
      - "&2Poziom{$colon} &6%level%"
      - "&2Koszt{$colon} &6%cost%"
    slot: 0
  change:
    name: "&6Zmień"
    material: DIAMOND_SWORD
    lore:
      - "&7Zmień typ swojego bohatera."
    slot: 1

  back:
    name: "&2Powrót"
    material: BARRIER
    lore:
      - "&6Powrót do ulepszeń bohatera."
    slot: 4
